return {
	settings = {
		css = {
			validate = true,
			lint = {
				compatibleVendorPrefixes = "warning",
				vendorPrefix = "warning",
				duplicateProperties = "warning",
				emptyRules = "warning",
				importStatement = "warning",
				boxModel = "warning",
				universalSelector = "warning",
				zeroUnits = "warning",
				fontFaceProperties = "warning",
				hexColorLength = "warning",
				argumentsInColorFunction = "warning",
				unknownProperties = "warning",
				ieHack = "warning",
				unknownVendorSpecificProperties = "warning",
				propertyIgnoredDueToDisplay = "warning",
				important = "warning",
				float = "warning",
				idSelector = "warning",
			},
		},
		scss = {
			validate = true,
			lint = {
				compatibleVendorPrefixes = "warning",
				vendorPrefix = "warning",
				duplicateProperties = "warning",
				emptyRules = "warning",
				importStatement = "warning",
				boxModel = "warning",
				universalSelector = "warning",
				zeroUnits = "warning",
				fontFaceProperties = "warning",
				hexColorLength = "warning",
				argumentsInColorFunction = "warning",
				unknownProperties = "warning",
				ieHack = "warning",
				unknownVendorSpecificProperties = "warning",
				propertyIgnoredDueToDisplay = "warning",
				important = "warning",
				float = "warning",
				idSelector = "warning",
			},
		},
		less = {
			validate = true,
			lint = {
				compatibleVendorPrefixes = "warning",
				vendorPrefix = "warning",
				duplicateProperties = "warning",
				emptyRules = "warning",
				importStatement = "warning",
				boxModel = "warning",
				universalSelector = "warning",
				zeroUnits = "warning",
				fontFaceProperties = "warning",
				hexColorLength = "warning",
				argumentsInColorFunction = "warning",
				unknownProperties = "warning",
				ieHack = "warning",
				unknownVendorSpecificProperties = "warning",
				propertyIgnoredDueToDisplay = "warning",
				important = "warning",
				float = "warning",
				idSelector = "warning",
			},
		},
	},
}
