return {
	"windwp/nvim-ts-autotag",
	event = "InsertEnter",
	dependencies = "nvim-treesitter/nvim-treesitter",
	config = function()
		require("nvim-ts-autotag").setup({
			filetypes = {
				"html",
				"xml",
				"javascriptreact",
				"typescriptreact",
				"vue",
				"svelte",
				"astro",
				"php",
				"markdown",
				"javascript",
				"typescript",
				"tsx",
				"jsx",
				"blade",
				"htmlangular",
			},
			skip_tags = {
				"area",
				"base",
				"br",
				"col",
				"command",
				"embed",
				"hr",
				"img",
				"slot",
				"input",
				"keygen",
				"link",
				"meta",
				"param",
				"source",
				"track",
				"wbr",
			},
		})
	end,
}
